# Issue 생성
POST localhost:8080/api/v1/issues
Content-Type: application/json

{
  "summary": "test",
  "description": "testContent",
  "type": "TASK",
  "priority": "LOW",
  "status": "TODO"
}

###
# Issue Status 조회
GET localhost:8080/api/v1/issues
Content-Type: application/json